# since Helio v1.9.0 - 跟随微服务`saas-api`配置文件更名为`admin-api`的变动
server:
  port: 7001

helio:
  knife4j:
    # knife4j显示配置
    title: 后台管理HTTP-API
    description: 后台管理HTTP-API
    version: 1.0.0
  web:
    logging:
      # 是否启用 Web 访问日志切面；开发、测试环境可以开启，生产环境不开启
      enabled: false
  i18n:
    # 是否对返回消息启用国际化翻译
    enabled: false

spring:
  messages:
    # 国际化资源目录，一般不做修改
    basename: i18n/messages
