# 最新的Redis配置节为：spring.data.redis
spring:
  data:
    redis:
      # Redis连接主机
      host: 127.0.0.1
      # Redis连接端口
      port: 6379
      # Redis登录密码；如果没有设置密码，请注释掉下面这行，避免向 Redis-server 发送 AUTH 鉴权请求，引发程序启动失败
      password:
      # Redis数据库序号
      database: 1
